In [7]:
from google.cloud import bigquery
import pandas as pd
from import_pack.import_data import grab_epl_data
from odds_featuring.odds_features import get_odds_final
from stats_pack.stats_features import stats_features
from average_pack.average import get_averages
from model_build.model_building import preprocess

In [2]:
df = grab_epl_data()

In [6]:
df

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,GBH,GBD,GBA,BSH,BSD,BSA,SBH,SBD,SBA,margin
0,E0,05/08/2022,20:00,Crystal Palace,Arsenal,0.0,2.0,A,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.0
1,E0,06/08/2022,12:30,Fulham,Liverpool,2.0,2.0,D,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,E0,06/08/2022,15:00,Bournemouth,Aston Villa,2.0,0.0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
3,E0,06/08/2022,15:00,Leeds,Wolves,2.0,1.0,H,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
4,E0,06/08/2022,15:00,Newcastle,Nott'm Forest,2.0,0.0,H,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6707,E0,07/05/06,NaN,Fulham,Middlesbrough,1.0,0.0,H,0.0,0.0,...,1.7,3.5,4.80,NaN,NaN,NaN,1.7,3.40,5.00,1.0
6708,E0,07/05/06,NaN,Man United,Charlton,4.0,0.0,H,3.0,0.0,...,1.2,6.0,13.00,NaN,NaN,NaN,1.2,5.75,13.00,4.0
6709,E0,07/05/06,NaN,Newcastle,Chelsea,1.0,0.0,H,0.0,0.0,...,2.9,3.0,2.50,NaN,NaN,NaN,2.8,3.25,2.40,1.0
6710,E0,07/05/06,NaN,Portsmouth,Liverpool,1.0,3.0,A,0.0,0.0,...,5.3,3.5,1.65,NaN,NaN,NaN,5.0,3.80,1.62,-2.0
6711,E0,07/05/06,NaN,West Ham,Tottenham,2.0,1.0,H,1.0,1.0,...,4.0,3.5,1.83,NaN,NaN,NaN,4.2,3.50,1.80,1.0

In [35]:
df.columns.values

array(['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG',
       'FTR', 'HTHG', 'HTAG', 'HTR', 'Referee', 'HS', 'AS', 'HST', 'AST',
       'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D',
       'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD',
       'PSA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA', 'MaxH', 'MaxD',
       'MaxA', 'AvgH', 'AvgD', 'AvgA', 'B365>2.5', 'B365<2.5', 'P>2.5',
       'P<2.5', 'Max>2.5', 'Max<2.5', 'Avg>2.5', 'Avg<2.5', 'AHh',
       'B365AHH', 'B365AHA', 'PAHH', 'PAHA', 'MaxAHH', 'MaxAHA', 'AvgAHH',
       'AvgAHA', 'B365CH', 'B365CD', 'B365CA', 'BWCH', 'BWCD', 'BWCA',
       'IWCH', 'IWCD', 'IWCA', 'PSCH', 'PSCD', 'PSCA', 'WHCH', 'WHCD',
       'WHCA', 'VCCH', 'VCCD', 'VCCA', 'MaxCH', 'MaxCD', 'MaxCA', 'AvgCH',
       'AvgCD', 'AvgCA', 'B365C>2.5', 'B365C<2.5', 'PC>2.5', 'PC<2.5',
       'MaxC>2.5', 'MaxC<2.5', 'AvgC>2.5', 'AvgC<2.5', 'AHCh', 'B365CAHH',
       'B365CAHA', 'PCAHH', 'PCAHA', 'MaxCAHH', 'MaxCAHA', 'AvgCAHH',
       'AvgCAHA', 'Bb1X2', 'BbMxH', 'BbAvH', 'BbMxD', 'BbAvD', 'BbMxA',
       'BbAvA', 'BbOU', 'BbMx>2.5', 'BbAv>2.5', 'BbMx<2.5', 'BbAv<2.5',
       'BbAH', 'BbAHh', 'BbMxAHH', 'BbAvAHH', 'BbMxAHA', 'BbAvAHA', 'LBH',
       'LBD', 'LBA', 'SJH', 'SJD', 'SJA', 'GBH', 'GBD', 'GBA', 'BSH',
       'BSD', 'BSA', 'SBH', 'SBD', 'SBA', 'margin'], dtype=object)

In [25]:
df = grab_epl_data()
df_final = stats_features(df).join(get_odds_final(df)).drop(columns=['margin'])
df_final.head()

(6712, 20) (6712, 20)
(6712, 2)

/Users/vicente/code/VicLanari/final-project-test/predict_epl_results/stats_pack/stats_features.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stats['THC'] = df_stats['HY'] + df_stats['HR']
/Users/vicente/code/VicLanari/final-project-test/predict_epl_results/stats_pack/stats_features.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stats['TAC'] = df_stats['AY'] + df_stats['AR']
/Users/vicente/code/VicLanari/final-project-test/predict_epl_results/odds_featuring/odds_features.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_odds["AHO"] = (df_odds["B365H"] + df_odds["BWH"] + df_odds["IWH"] + df_odds["WHH"] + df_odds["VCH"])/5
/Users/vicente/code/VicLanari/final-project-test/predict_epl_results/odds_featuring/odds_features.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_odds["AAO"] = (df_odds["B365A"] + df_odds["BWA"] + df_odds["IWA"] + df_odds["WHA"] + df_odds["VCA"])/5

   AST   HST    HC   AC  THC  TAC    AAO     AHO
0  2.0   2.0   3.0  5.0  1.0  2.0  1.854   4.366
1  4.0   3.0   4.0  4.0  2.0  0.0  1.264  11.600
2  2.0   3.0   5.0  5.0  3.0  3.0  2.020   3.730
3  6.0   4.0   6.0  4.0  2.0  0.0  3.120   2.280
4  0.0  10.0  11.0  1.0  0.0  3.0  5.400   1.650

In [30]:
df_final.loc[df_final['AST'] == 8.0].loc[df_final['HST'] == 12.0]

      AST   HST    HC    AC  THC  TAC    AAO     AHO
3769  8.0  12.0   8.0   8.0  0.0  2.0  4.220   1.852
3860  8.0  12.0   5.0   6.0  0.0  1.0  7.220   1.456
3927  8.0  12.0   5.0   2.0  1.0  3.0  4.410   1.854
4448  8.0  12.0   0.0   0.0  1.0  2.0  1.238  12.700
4491  8.0  12.0   5.0   4.0  1.0  2.0  2.540   2.772
4556  8.0  12.0  12.0   6.0  2.0  2.0  6.080   1.592
4741  8.0  12.0   5.0  10.0  1.0  0.0  3.460   2.140
4872  8.0  12.0   5.0   6.0  0.0  3.0  1.924   3.870
4877  8.0  12.0  11.0   5.0  1.0  1.0  7.450   1.418
4945  8.0  12.0   4.0   8.0  4.0  3.0  1.370   8.550
5642  8.0  12.0   3.0   9.0  0.0  0.0    NaN     NaN
5644  8.0  12.0  10.0   2.0  1.0  0.0    NaN     NaN
5766  8.0  12.0   3.0   6.0  0.0  3.0  6.300   1.500
5839  8.0  12.0   4.0   7.0  1.0  1.0  2.940   2.330

In [17]:
def upload_historic_data():
    """
    This function will return data that is selected but not preprocessed
    """
    PROJECT = "predicting-epl-results"
    DATASET = "processed_data"
    TABLE = "processed"

    table = f"{PROJECT}.{DATASET}.{TABLE}"

    df = grab_epl_data()
    df_final = stats_features(df).join(get_odds_final(df)).drop(columns=['margin'])
    df_final = df_final.dropna()
    client = bigquery.Client(project=PROJECT)

    write_mode = "WRITE_TRUNCATE" # or "WRITE_APPEND"
    job_config = bigquery.LoadJobConfig(write_disposition=write_mode)

    job = client.load_table_from_dataframe(df_final, table, job_config=job_config)
    result = job.result()
    return None

In [16]:
def upload_raw_data():
    PROJECT = "predicting-epl-results"
    DATASET = "raw_data"
    TABLE = "updated_game_history"

    table = f"{PROJECT}.{DATASET}.{TABLE}"

    df = grab_epl_data()

    client = bigquery.Client(project=PROJECT)

    write_mode = "WRITE_TRUNCATE" # or "WRITE_APPEND"
    job_config = bigquery.LoadJobConfig(write_disposition=write_mode)

    job = client.load_table_from_dataframe(df, table, job_config=job_config)
    result = job.result()
    return None

In [24]:
upload_historic_data()

/Users/vicente/code/VicLanari/final-project-test/predict_epl_results/stats_pack/stats_features.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stats['THC'] = df_stats['HY'] + df_stats['HR']
/Users/vicente/code/VicLanari/final-project-test/predict_epl_results/stats_pack/stats_features.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_stats['TAC'] = df_stats['AY'] + df_stats['AR']
/Users/vicente/code/VicLanari/final-project-test/predict_epl_results/odds_featuring/odds_features.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_odds["AHO"] = (df_odds["B365H"] + df_odds["BWH"] + df_odds["IWH"] + df_odds["WHH"] + df_odds["VCH"])/5
/Users/vicente/code/VicLanari/final-project-test/predict_epl_results/odds_featuring/odds_features.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_odds["AAO"] = (df_odds["B365A"] + df_odds["BWA"] + df_odds["IWA"] + df_odds["WHA"] + df_odds["VCA"])/5

(6712, 20) (6712, 20)
(6712, 2)

Forbidden: 403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/predicting-epl-results/jobs?uploadType=multipart: Access Denied: Project predicting-epl-results: User does not have bigquery.jobs.create permission in project predicting-epl-results.

In [33]:
df_final['idx'] = [i+1 for i in range(len(df_final))]

      AST  HST  HC  AC  THC  TAC  AAO  AHO   idx
3291  NaN  NaN NaN NaN  NaN  NaN  NaN  NaN  3292